name: "Run Scanner at scale"

# concurrency config
config:
  workers: 10

# variables
vars:
  - name: username
    value: dmdhrumilmistry

  - name: test
    value: "true"

file_var:
  name: repo
  path: ./test/repos.txt # list of repo on each line
  separator: "\n"

pipeline:
  - name: "Run 'whoami'"
    cmd: "whoami"
    store: true # store stdout, stderr
    ignore_failure: true # everything except 0 will be treated as error

  - name: "print repo name"
    cmd: "echo ${username} ${repo}"
    store: true

  - name: "print stored vars"
    cmd: "echo '${r.0.stdout} - ${r.1.stdout}'" # access result from previous pipeline stages

    
      

